"""Word placement and word-search puzzle generation."""

from puzzle_portrait.wordsearch.directions import (
    BACKWARD_DIRECTIONS,
    DIAGONAL_DIRECTIONS,
    DIRECTIONS,
    DOWN,
    DOWN_LEFT,
    DOWN_RIGHT,
    FORWARD_DIRECTIONS,
    HORIZONTAL_DIRECTIONS,
    LEFT,
    RIGHT,
    UP,
    UP_LEFT,
    UP_RIGHT,
    VERTICAL_DIRECTIONS,
    Direction,
    axis_of,
    direction_weights_from_axes,
    normalize_direction_weights,
    placement_directions,
)
from puzzle_portrait.wordsearch.fill import fill_empty_random
from puzzle_portrait.wordsearch.generate import WordSearch, generate_word_search
from puzzle_portrait.wordsearch.letter_grid import EMPTY, LetterGrid
from puzzle_portrait.wordsearch.placement import (
    Placement,
    can_place,
    place_word,
    place_word_randomly,
)
from puzzle_portrait.wordsearch.score import (
    center_out_score,
    choose_scored_placement,
    distance_from_center,
    placement_centroid,
    placement_cells,
    placement_middle_letter,
    score_placement,
    spatial_score,
    target_spread_radius,
)
from puzzle_portrait.wordsearch.verify import (
    VerificationReport,
    WordResult,
    find_word,
    verify_words,
)

__all__ = [
    "BACKWARD_DIRECTIONS",
    "DIAGONAL_DIRECTIONS",
    "DIRECTIONS",
    "DOWN",
    "DOWN_LEFT",
    "DOWN_RIGHT",
    "EMPTY",
    "FORWARD_DIRECTIONS",
    "HORIZONTAL_DIRECTIONS",
    "LEFT",
    "RIGHT",
    "UP",
    "UP_LEFT",
    "UP_RIGHT",
    "VERTICAL_DIRECTIONS",
    "Direction",
    "axis_of",
    "choose_scored_placement",
    "direction_weights_from_axes",
    "normalize_direction_weights",
    "placement_directions",
    "LetterGrid",
    "Placement",
    "VerificationReport",
    "WordResult",
    "WordSearch",
    "can_place",
    "center_out_score",
    "distance_from_center",
    "fill_empty_random",
    "find_word",
    "generate_word_search",
    "place_word",
    "place_word_randomly",
    "placement_cells",
    "placement_centroid",
    "placement_middle_letter",
    "score_placement",
    "spatial_score",
    "target_spread_radius",
    "verify_words",
]
